In [1]:
suppressPackageStartupMessages({
    library(tidyverse)
    library(kSamples)
    library(glmnet)
    library(ppcor)
    library(Signac)
    library(Seurat)
    library(argparse)
    library(logging)
    library(reshape2)
})

Warning message:
“package ‘tibble’ was built under R version 4.3.2”
Warning message:
“package ‘stringr’ was built under R version 4.3.2”

In [2]:
SINCERITITES <- dget("/home/chenxufeng/WorkSpace/scMagnify/scMagnify-benchmark/scripts/SINCERITIES.R")

In [71]:
path <- "/home/chenxufeng/picb_cxf/Data/scMultiSim/bench_grn/datasets/grn1139_noise_tree1_1000_cells1139_genes_sigma0.1_1/"

In [72]:
ExprMatrix <- read.csv(file = paste0(path , "ExpressionData.csv"), row.names = 1)

In [73]:
head(ExprMatrix)

      cell1    cell2    cell3    cell4 cell5    cell6    cell7    cell8
gene1 0.000000 0.000000 0.000000 0     0.000000 0.000000 0.000000 0.000000
gene2 0.000000 0.000000 0.000000 0     0.000000 0.000000 0.000000 0.000000
gene3 7.693487 7.011227 6.857981 0     6.087463 7.629357 7.577429 5.426265
gene4 0.000000 0.000000 0.000000 0     0.000000 0.000000 0.000000 6.426265
gene5 4.584963 0.000000 4.087463 0     3.459432 2.584963 5.169925 7.000000
gene6 5.209453 5.906891 5.491853 0     4.321928 0.000000 0.000000 0.000000
      cell9    cell10   ⋯ cell991  cell992  cell993  cell994  cell995  cell996
gene1 0.000000 0.000000 ⋯ 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
gene2 0.000000 0.000000 ⋯ 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
gene3 7.839204 7.209453 ⋯ 6.108524 6.022368 6.022368 7.076816 5.392317 5.857981
gene4 0.000000 0.000000 ⋯ 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
gene5 0.000000 0.000000 ⋯ 4.000000 0.000000 5.426265 0.000000 3.700440 0.000000
gene6 3.459432 5.000000 ⋯ 0.000000 3.169925 0.000000 0.000000 2.807355 0.000000
      cell997  cell998  cell999 cell1000
gene1 0.000000 0.000000 0.00000 0.000000
gene2 0.000000 0.000000 0.00000 0.000000
gene3 7.294621 6.714246 6.00000 5.087463
gene4 0.000000 0.000000 0.00000 0.000000
gene5 5.247928 0.000000 4.70044 6.285402
gene6 4.700440 0.000000 6.00000 0.000000

In [74]:
sds <- apply(ExprMatrix, 2, sd)
ExprMatrix<- ExprMatrix[, which(sds > quantile(sds, prob = 0.2))]

In [75]:
Pseudotime <- read.csv(file = paste0(path , "PseudoTime.csv"))

In [76]:
sorted_indices <- order(Pseudotime$palantir_pseudotime)
bin_indices <- cut(seq_along(sorted_indices), breaks = 10, labels = FALSE) - 1

Pseudotime$time <- NA
Pseudotime$time[sorted_indices] <- bin_indices

In [77]:
preprocess <- function(df){
  
  NAIdx <- is.na(apply(df,1,sum))
  df <- df[!NAIdx,]
  
  totDATA <- df[,1:dim(df)[2]-1]
  timeline <- df[,dim(df)[2]]
  DATA.time <- sort(unique(timeline))
  DATA.num_time_points <- length(DATA.time)
  DATA.totDATA <- matrix(ncol = dim(df)[2]-1)
  DATA.timeline <- vector()
  
  for (k in 1:DATA.num_time_points) {
    I <- which(timeline==DATA.time[k])
    DATA.totDATA <- rbind(DATA.totDATA,as.matrix(totDATA[I,]))
    DATA.timeline <- c(DATA.timeline,timeline[I])
  }
  DATA.totDATA <- DATA.totDATA[-1,]
  DATA.totDATA[is.na(DATA.totDATA)] <- 0
  DATA.numGENES <- dim(DATA.totDATA)[2]
  
  DATA.genes <- colnames(df)[1:dim(df)[2]-1]
  
  DATA.singleCELLdata <- by(DATA.totDATA,DATA.timeline,identity)
  DATA <- list(time=DATA.time,num_time_points=DATA.num_time_points,
               totDATA=DATA.totDATA,timeline=DATA.timeline,numGENES=DATA.numGENES,
               genes=DATA.genes,singleCELLdata=DATA.singleCELLdata)
  return(DATA)
}

In [78]:
DATA <- preprocess(cbind(t(ExprMatrix), Pseudotime$time))

Warning message in cbind(t(ExprMatrix), Pseudotime$time):
“number of rows of result is not a multiple of vector length (arg 2)”

In [79]:
str(DATA)

List of 7
 $ time           : num [1:9] 0 1 2 3 4 5 6 7 8
 $ num_time_points: int 9
 $ totDATA        : num [1:800, 1:1250] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:800] "cell2" "cell3" "cell4" "cell5" ...
  .. ..$ : chr [1:1250] "gene1" "gene2" "gene3" "gene4" ...
 $ timeline       : Named num [1:800] 0 0 0 0 0 0 0 0 0 0 ...
  ..- attr(*, "names")= chr [1:800] "cell2" "cell3" "cell4" "cell5" ...
 $ numGENES       : int 1250
 $ genes          : chr [1:1250] "gene1" "gene2" "gene3" "gene4" ...
 $ singleCELLdata :List of 9
  ..$ 0:'data.frame':	100 obs. of  1250 variables:
  .. ..$ gene1   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene2   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene3   : num [1:100] 7.01 6.86 0 6.09 7.63 ...
  .. ..$ gene4   : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene5   : num [1:100] 0 4.09 0 3.46 2.58 ...
  .. ..$ gene6   : num [1:100] 5.91 5.49 0 4.32 0 ...
  .. ..$ gene7   : num [1:100] 0 0 4.91 6.61 4.95 ...
  .. ..$ gene8   : num [1:100] 6.69 6.81 5.55 5 2 ...
  .. ..$ gene9   : num [1:100] 8.17 4.95 6.17 0 5.13 ...
  .. ..$ gene10  : num [1:100] 8.03 9.58 10.51 9.7 10.12 ...
  .. ..$ gene11  : num [1:100] 4.81 6.98 5.32 5.29 6.38 ...
  .. ..$ gene12  : num [1:100] 7.28 7.26 7.77 5.49 6.57 ...
  .. ..$ gene13  : num [1:100] 0 5.58 0 0 0 ...
  .. ..$ gene14  : num [1:100] 6.07 4.25 7.47 0 6.04 ...
  .. ..$ gene15  : num [1:100] 5 2.81 6.79 4.75 7.16 ...
  .. ..$ gene16  : num [1:100] 1 0 6.32 5.25 5.78 ...
  .. ..$ gene17  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene18  : num [1:100] 6.19 3.7 7.36 6.09 7.28 ...
  .. ..$ gene19  : num [1:100] 5.73 6.23 2.58 0 2.32 ...
  .. ..$ gene20  : num [1:100] 6.11 5.86 7.82 8.58 7.3 ...
  .. ..$ gene21  : num [1:100] 7.36 5.95 6.07 4.91 6.78 ...
  .. ..$ gene22  : num [1:100] 5.7 7.6 7.56 8.82 7.41 ...
  .. ..$ gene23  : num [1:100] 0 7.75 4.95 0 5.61 ...
  .. ..$ gene24  : num [1:100] 0 6.04 0 4.52 4.58 ...
  .. ..$ gene25  : num [1:100] 4.25 5.04 6.23 6.58 7.23 ...
  .. ..$ gene26  : num [1:100] 0 4.25 6.27 0 4 ...
  .. ..$ gene27  : num [1:100] 7.87 7.44 7.21 8.18 7.55 ...
  .. ..$ gene28  : num [1:100] 6.69 3.81 0 2.81 0 ...
  .. ..$ gene29  : num [1:100] 3 0 0 6.74 0 ...
  .. ..$ gene30  : num [1:100] 4.32 7.15 9.49 6.02 7.68 ...
  .. ..$ gene31  : num [1:100] 9.02 8.07 8.7 8.03 7.4 ...
  .. ..$ gene32  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene33  : num [1:100] 5.61 3 5.32 6.04 0 ...
  .. ..$ gene34  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene35  : num [1:100] 2.81 5.21 0 7.18 0 ...
  .. ..$ gene36  : num [1:100] 6.6 6.58 7.77 7.91 8.51 ...
  .. ..$ gene37  : num [1:100] 8.32 7.63 8.37 8.78 8.03 ...
  .. ..$ gene38  : num [1:100] 6.93 4 4.17 6.41 5.86 ...
  .. ..$ gene39  : num [1:100] 0 6.3 5.13 5.91 6.29 ...
  .. ..$ gene40  : num [1:100] 6.83 7.45 5.55 5 7.03 ...
  .. ..$ gene41  : num [1:100] 8.02 7.82 8.62 8.46 8.1 ...
  .. ..$ gene42  : num [1:100] 6.34 5.36 4.52 6.54 5.81 ...
  .. ..$ gene43  : num [1:100] 5.78 0 5.61 6.83 2.81 ...
  .. ..$ gene44  : num [1:100] 6.57 6.02 5.43 7.04 5.13 ...
  .. ..$ gene45  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene46  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene47  : num [1:100] 4.91 6.27 7.32 4.09 5.81 ...
  .. ..$ gene48  : num [1:100] 6.21 3.17 6.3 3.7 4.7 ...
  .. ..$ gene49  : num [1:100] 5.46 2.58 5.32 5.75 4.75 ...
  .. ..$ gene50  : num [1:100] 0 0 0 1 3.58 ...
  .. ..$ gene51  : num [1:100] 0 5.17 0 0 0 ...
  .. ..$ gene52  : num [1:100] 0 7.41 7.46 0 7.28 ...
  .. ..$ gene53  : num [1:100] 6.44 5.04 0 0 4.09 ...
  .. ..$ gene54  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene55  : num [1:100] 0 0 0 4 0 ...
  .. ..$ gene56  : num [1:100] 0 0 2.58 0 0 ...
  .. ..$ gene57  : num [1:100] 4.64 7.43 8.69 5.7 6.3 ...
  .. ..$ gene58  : num [1:100] 3 5.75 7.99 6.82 7.11 ...
  .. ..$ gene59  : num [1:100] 0 5.73 4.64 0 6.23 ...
  .. ..$ gene60  : num [1:100] 6.23 7.14 7.74 6.82 7.41 ...
  .. ..$ gene61  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene62  : num [1:100] 0 5.81 5.46 3.58 3.58 ...
  .. ..$ gene63  : num [1:100] 6.64 6.38 6.15 0 6.55 ...
  .. ..$ gene64  : num [1:100] 0 0 5.36 0 0 ...
  .. ..$ gene65  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene66  : num [1:100] 0 5.29 8.24 6.51 5.83 ...
  .. ..$ gene67  : num [1:100] 6.46 7.02 7.17 5.86 3.58 ...
  .. ..$ gene68  : num [1:100] 7.26 8.31 7.36 7.14 6.85 ...
  .. ..$ gene69  : num [1:100] 6.66 5.43 5.88 6.11 4.46 ...
  .. ..$ gene70  : num [1:100] 7.99 7.84 9.08 7.6 7.38 ...
  .. ..$ gene71  : num [1:100] 0 0 5.81 2.81 0 ...
  .. ..$ gene72  : num [1:100] 7.21 7.11 7.6 8.44 7.56 ...
  .. ..$ gene73  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene74  : num [1:100] 8.42 8.67 5.67 8.88 8.14 ...
  .. ..$ gene75  : num [1:100] 6.55 6.38 4.52 4.32 3.81 ...
  .. ..$ gene76  : num [1:100] 4.46 3.81 0 6.02 1.58 ...
  .. ..$ gene77  : num [1:100] 0 5.86 4.7 0 4.64 ...
  .. ..$ gene78  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene79  : num [1:100] 7.35 5.61 6.83 6.79 7.25 ...
  .. ..$ gene80  : num [1:100] 8.97 8.84 8.83 8.6 8.12 ...
  .. ..$ gene81  : num [1:100] 7.17 6.36 0 4.52 5.25 ...
  .. ..$ gene82  : num [1:100] 6.66 4.09 7.63 7.97 5.17 ...
  .. ..$ gene83  : num [1:100] 7.18 7.54 8.12 7.54 7.19 ...
  .. ..$ gene84  : num [1:100] 0 0 0 4.25 0 ...
  .. ..$ gene85  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene86  : num [1:100] 0 3.58 4.32 2.58 5.46 ...
  .. ..$ gene87  : num [1:100] 4.52 4.32 0 5.88 3.7 ...
  .. ..$ gene88  : num [1:100] 0 0 6.13 0 7.12 ...
  .. ..$ gene89  : num [1:100] 3.7 4.91 4.32 0 2.32 ...
  .. ..$ gene90  : num [1:100] 0 0 6.11 6.11 0 ...
  .. ..$ gene91  : num [1:100] 0 4.46 3.58 4.81 0 ...
  .. ..$ gene92  : num [1:100] 5.73 5.09 4.58 8.46 8.12 ...
  .. ..$ gene93  : num [1:100] 5.67 5.67 0 5.78 5.36 ...
  .. ..$ gene94  : num [1:100] 0 5.73 0 3.7 5.25 ...
  .. ..$ gene95  : num [1:100] 0 0 0 4.91 5 ...
  .. ..$ gene96  : num [1:100] 5.88 5.55 6.29 7.33 6.58 ...
  .. ..$ gene97  : num [1:100] 3.32 0 3 5.04 4.46 ...
  .. ..$ gene98  : num [1:100] 6.79 4.95 7.82 5.46 5.49 ...
  .. ..$ gene99  : num [1:100] 8.98 9.29 5.17 4.86 8.06 ...
  .. .. [list output truncated]
  ..$ 1:'data.frame':	100 obs. of  1250 variables:
  .. ..$ gene1   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene2   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene3   : num [1:100] 7.84 7.21 7.77 7.55 7.09 ...
  .. ..$ gene4   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene5   : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene6   : num [1:100] 3.46 5 6.13 5.81 0 ...
  .. ..$ gene7   : num [1:100] 3.7 0 0 4.09 0 ...
  .. ..$ gene8   : num [1:100] 2 6.27 0 4.91 4.25 ...
  .. ..$ gene9   : num [1:100] 5.46 5.64 4 5.04 5.49 ...
  .. ..$ gene10  : num [1:100] 10.09 9.27 10.29 9.98 10.21 ...
  .. ..$ gene11  : num [1:100] 6.54 4.09 3.7 7.58 5.21 ...
  .. ..$ gene12  : num [1:100] 6.13 8.08 7.92 7.64 5.43 ...
  .. ..$ gene13  : num [1:100] 0 0 4.95 0 0 ...
  .. ..$ gene14  : num [1:100] 0 1.58 3.58 6.38 0 ...
  .. ..$ gene15  : num [1:100] 5.49 4.25 3.7 6.07 5.25 ...
  .. ..$ gene16  : num [1:100] 3 0 0 5.75 0 ...
  .. ..$ gene17  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene18  : num [1:100] 8.16 7.68 5.64 7.29 6.38 ...
  .. ..$ gene19  : num [1:100] 5.55 0 6.27 0 0 ...
  .. ..$ gene20  : num [1:100] 7.44 7.75 6.36 7.08 8.01 ...
  .. ..$ gene21  : num [1:100] 4.09 6.27 7.34 6.19 5.43 ...
  .. ..$ gene22  : num [1:100] 7.36 5.98 7.69 7.91 5.83 ...
  .. ..$ gene23  : num [1:100] 4.32 0 0 4 4.7 ...
  .. ..$ gene24  : num [1:100] 2.81 4.32 5.73 0 0 ...
  .. ..$ gene25  : num [1:100] 6.32 7.12 7.32 8.52 6.48 ...
  .. ..$ gene26  : num [1:100] 5.36 4.58 0 0 3.7 ...
  .. ..$ gene27  : num [1:100] 7.22 6.38 6.87 6.83 7.43 ...
  .. ..$ gene28  : num [1:100] 2.58 6.09 4.7 3.7 3.32 ...
  .. ..$ gene29  : num [1:100] 0 2 1 4.7 0 ...
  .. ..$ gene30  : num [1:100] 8.5 7.83 7.57 6.93 7.09 ...
  .. ..$ gene31  : num [1:100] 7.85 6.38 8.46 8.54 8.82 ...
  .. ..$ gene32  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene33  : num [1:100] 3 0 5.49 0 0 ...
  .. ..$ gene34  : num [1:100] 5.13 0 0 0 0 ...
  .. ..$ gene35  : num [1:100] 1.58 4.7 6.64 7.48 5.36 ...
  .. ..$ gene36  : num [1:100] 7.92 6.85 9.72 8.02 7.63 ...
  .. ..$ gene37  : num [1:100] 8.12 0 6.85 8.5 0 ...
  .. ..$ gene38  : num [1:100] 7.2 6.3 0 5.25 6.98 ...
  .. ..$ gene39  : num [1:100] 5.61 4.91 6.49 6.46 4.09 ...
  .. ..$ gene40  : num [1:100] 3.7 6.55 3.58 6.15 5.7 ...
  .. ..$ gene41  : num [1:100] 7.43 8.95 9.48 6.95 8.67 ...
  .. ..$ gene42  : num [1:100] 7.25 6.02 7.15 7.64 7.59 ...
  .. ..$ gene43  : num [1:100] 1 5.55 0 0 3.91 ...
  .. ..$ gene44  : num [1:100] 6.69 4.95 7.08 7.1 4.75 ...
  .. ..$ gene45  : num [1:100] 0 0 0 6.17 0 ...
  .. ..$ gene46  : num [1:100] 0 0 0 3.17 0 ...
  .. ..$ gene47  : num [1:100] 6.11 0 4.39 4.75 6.58 ...
  .. ..$ gene48  : num [1:100] 3.17 5.67 0 5.17 5.04 ...
  .. ..$ gene49  : num [1:100] 6.19 6.92 4.95 6.52 5.52 ...
  .. ..$ gene50  : num [1:100] 0 0 4.09 0 3.81 ...
  .. ..$ gene51  : num [1:100] 5.36 0 5.49 0 3 ...
  .. ..$ gene52  : num [1:100] 7.54 0 7.15 0 6.55 ...
  .. ..$ gene53  : num [1:100] 6.29 5.75 6.87 5.29 0 ...
  .. ..$ gene54  : num [1:100] 3 0 0 0 4.52 ...
  .. ..$ gene55  : num [1:100] 5.13 4.86 0 0 0 ...
  .. ..$ gene56  : num [1:100] 4.81 0 7.51 0 2 ...
  .. ..$ gene57  : num [1:100] 7.43 7.37 5.43 8.1 7.11 ...
  .. ..$ gene58  : num [1:100] 6.25 7.88 7.41 8.32 6.04 ...
  .. ..$ gene59  : num [1:100] 0 0 6.07 3.17 0 ...
  .. ..$ gene60  : num [1:100] 8.15 7.11 7.86 8.13 8 ...
  .. ..$ gene61  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene62  : num [1:100] 0 5.04 0 3.32 0 ...
  .. ..$ gene63  : num [1:100] 0 0 5.13 0 7.63 ...
  .. ..$ gene64  : num [1:100] 0 0 0 5.52 0 ...
  .. ..$ gene65  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene66  : num [1:100] 7.43 6.48 7.77 6.27 4.39 ...
  .. ..$ gene67  : num [1:100] 6.25 7.06 4.09 6.64 7.45 ...
  .. ..$ gene68  : num [1:100] 6.38 7.06 4.25 7.85 7.73 ...
  .. ..$ gene69  : num [1:100] 6.27 0 8.44 5.09 5.75 ...
  .. ..$ gene70  : num [1:100] 6.52 7.5 7.58 8.41 6.17 ...
  .. ..$ gene71  : num [1:100] 5.86 0 3.17 0 3.91 ...
  .. ..$ gene72  : num [1:100] 7.76 7.11 6.86 7.89 7.72 ...
  .. ..$ gene73  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene74  : num [1:100] 7.16 8.12 8.89 7.63 8.06 ...
  .. ..$ gene75  : num [1:100] 4.7 5.32 6.38 3.7 7.19 ...
  .. ..$ gene76  : num [1:100] 6.77 5 4.81 2.58 4.64 ...
  .. ..$ gene77  : num [1:100] 3.58 2.32 7.1 7.06 7.22 ...
  .. ..$ gene78  : num [1:100] 4.17 0 1.58 3.91 0 ...
  .. ..$ gene79  : num [1:100] 7.24 6.27 6.77 8.1 8.08 ...
  .. ..$ gene80  : num [1:100] 8.25 9 8.33 8.3 9.36 ...
  .. ..$ gene81  : num [1:100] 6.63 4.09 6.77 7.25 6.7 ...
  .. ..$ gene82  : num [1:100] 6.88 6.39 0 6.88 7.34 ...
  .. ..$ gene83  : num [1:100] 8.06 8.28 6.97 7.64 8.46 ...
  .. ..$ gene84  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene85  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene86  : num [1:100] 0 0 3.58 0 4.7 ...
  .. ..$ gene87  : num [1:100] 0 6.46 0 3.7 0 ...
  .. ..$ gene88  : num [1:100] 0 4.32 0 7.33 0 ...
  .. ..$ gene89  : num [1:100] 0 0 5.32 5.49 0 ...
  .. ..$ gene90  : num [1:100] 5.93 6.93 0 5.43 0 ...
  .. ..$ gene91  : num [1:100] 0 0 4.64 6.04 5.81 ...
  .. ..$ gene92  : num [1:100] 5.25 7.19 7.86 6.69 0 ...
  .. ..$ gene93  : num [1:100] 5.93 6.02 6.74 0 6.55 ...
  .. ..$ gene94  : num [1:100] 5.95 0 5.55 5.13 0 ...
  .. ..$ gene95  : num [1:100] 4 0 0 5.09 5.95 ...
  .. ..$ gene96  : num [1:100] 6.86 7.14 6.19 6.23 6.99 ...
  .. ..$ gene97  : num [1:100] 0 0 0 5.17 3.7 ...
  .. ..$ gene98  : num [1:100] 6.66 7.42 5.83 7.69 6.57 ...
  .. ..$ gene99  : num [1:100] 8.06 8.63 8.46 9.44 9.6 ...
  .. .. [list output truncated]
  ..$ 2:'data.frame':	100 obs. of  1250 variables:
  .. ..$ gene1   : num [1:100] 0 0 0 2.58 0 ...
  .. ..$ gene2   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene3   : num [1:100] 8.55 7.03 6.82 8.22 6.25 ...
  .. ..$ gene4   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene5   : num [1:100] 0 4.32 0 3.32 0 ...
  .. ..$ gene6   : num [1:100] 0 0 3 2.58 0 ...
  .. ..$ gene7   : num [1:100] 3.81 0 7.47 5.49 3 ...
  .. ..$ gene8   : num [1:100] 6.17 5.29 4.39 1 4.52 ...
  .. ..$ gene9   : num [1:100] 4.95 6.41 6.61 3.7 6.17 ...
  .. ..$ gene10  : num [1:100] 9.04 8.99 8.61 9.53 8.92 ...
  .. ..$ gene11  : num [1:100] 6.34 6.92 5.39 5.46 5.43 ...
  .. ..$ gene12  : num [1:100] 5.36 6.7 5.36 6.41 5.17 ...
  .. ..$ gene13  : num [1:100] 0 0 5.43 0 0 ...
  .. ..$ gene14  : num [1:100] 6.07 6.67 5.46 0 3.58 ...
  .. ..$ gene15  : num [1:100] 6.88 6.92 6.87 5 6.15 ...
  .. ..$ gene16  : num [1:100] 0 6.19 4.7 6.34 0 ...
  .. ..$ gene17  : num [1:100] 0 0 0 0 0 0 0 0 1 0 ...
  .. ..$ gene18  : num [1:100] 6.97 7.86 6.39 6.46 4.64 ...
  .. ..$ gene19  : num [1:100] 5.36 3.58 0 0 5.67 ...
  .. ..$ gene20  : num [1:100] 4.95 8.11 7.79 7.58 7.73 ...
  .. ..$ gene21  : num [1:100] 5.49 5.55 5.98 5.04 3 ...
  .. ..$ gene22  : num [1:100] 8.03 7.22 7.79 8.1 6.85 ...
  .. ..$ gene23  : num [1:100] 6.15 4 5.46 5.36 3.32 ...
  .. ..$ gene24  : num [1:100] 2.58 0 4.86 4.7 0 ...
  .. ..$ gene25  : num [1:100] 6.13 6 6.49 7.36 8.15 ...
  .. ..$ gene26  : num [1:100] 5 0 0 5.7 0 ...
  .. ..$ gene27  : num [1:100] 6.99 7.42 7.22 7.67 8.65 ...
  .. ..$ gene28  : num [1:100] 3.7 6.87 5.55 5.49 5.17 ...
  .. ..$ gene29  : num [1:100] 3.46 0 0 0 0 ...
  .. ..$ gene30  : num [1:100] 7.32 8.54 8.1 9.01 9.55 ...
  .. ..$ gene31  : num [1:100] 5.64 5.09 7.39 6.36 6.27 ...
  .. ..$ gene32  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene33  : num [1:100] 5.17 0 5.21 4.86 0 ...
  .. ..$ gene34  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene35  : num [1:100] 0 5.25 2 4.32 0 ...
  .. ..$ gene36  : num [1:100] 7.19 8.61 8.67 5.88 0 ...
  .. ..$ gene37  : num [1:100] 2.58 3.91 2 0 8.71 ...
  .. ..$ gene38  : num [1:100] 4.58 7.17 6.69 7.12 6.52 ...
  .. ..$ gene39  : num [1:100] 4.32 6.41 2.32 6.04 0 ...
  .. ..$ gene40  : num [1:100] 5.83 5.86 5 3 6.63 ...
  .. ..$ gene41  : num [1:100] 7.52 7.27 8.36 7.84 8.57 ...
  .. ..$ gene42  : num [1:100] 6.27 5.39 5.32 7.03 5.52 ...
  .. ..$ gene43  : num [1:100] 1 7.33 0 0 0 ...
  .. ..$ gene44  : num [1:100] 0 6.99 4.81 5 0 ...
  .. ..$ gene45  : num [1:100] 0 0 2.81 0 0 ...
  .. ..$ gene46  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene47  : num [1:100] 0 6.25 6.11 4.91 6.6 ...
  .. ..$ gene48  : num [1:100] 0 0 4.25 0 3.91 ...
  .. ..$ gene49  : num [1:100] 6.49 5.98 6.07 5.04 6.07 ...
  .. ..$ gene50  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene51  : num [1:100] 5.09 0 5.09 0 0 ...
  .. ..$ gene52  : num [1:100] 4.39 0 0 0 0 ...
  .. ..$ gene53  : num [1:100] 2 5.95 0 3.17 2.81 ...
  .. ..$ gene54  : num [1:100] 4.46 4.25 4.32 7.17 4.64 ...
  .. ..$ gene55  : num [1:100] 5 0 0 5.13 2.81 ...
  .. ..$ gene56  : num [1:100] 0 4.52 0 5.43 0 ...
  .. ..$ gene57  : num [1:100] 8.06 6.86 7.11 6.3 5.78 ...
  .. ..$ gene58  : num [1:100] 7.19 7.27 7.59 7.04 6.94 ...
  .. ..$ gene59  : num [1:100] 4.17 0 4.46 0 3.17 ...
  .. ..$ gene60  : num [1:100] 6.57 8.52 7.99 7.2 7.41 ...
  .. ..$ gene61  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene62  : num [1:100] 1.58 0 0 5.17 4.95 ...
  .. ..$ gene63  : num [1:100] 5.64 0 4.46 0 0 ...
  .. ..$ gene64  : num [1:100] 0 0 0 0 6.83 ...
  .. ..$ gene65  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene66  : num [1:100] 8.23 4.95 4.75 6.29 7.15 ...
  .. ..$ gene67  : num [1:100] 5.93 6.44 7.32 7.09 6.17 ...
  .. ..$ gene68  : num [1:100] 6.48 4.75 6.49 6.32 2.81 ...
  .. ..$ gene69  : num [1:100] 0 5.39 3.7 6.13 4.17 ...
  .. ..$ gene70  : num [1:100] 8.03 7.02 8.01 6.97 6.48 ...
  .. ..$ gene71  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene72  : num [1:100] 7.11 7.63 7.38 5.64 6.94 ...
  .. ..$ gene73  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene74  : num [1:100] 7.76 7.52 8.61 7.7 7.69 ...
  .. ..$ gene75  : num [1:100] 6.92 7.52 6.41 3.58 7.86 ...
  .. ..$ gene76  : num [1:100] 3.91 4.95 0 4.95 3 ...
  .. ..$ gene77  : num [1:100] 4.52 6.92 0 6.02 5.64 ...
  .. ..$ gene78  : num [1:100] 4.58 0 5.09 0 4 ...
  .. ..$ gene79  : num [1:100] 3 6.46 7.39 6.79 7.23 ...
  .. ..$ gene80  : num [1:100] 8.23 9.06 9.35 8.61 9.56 ...
  .. ..$ gene81  : num [1:100] 6.99 6.02 6.6 0 6.77 ...
  .. ..$ gene82  : num [1:100] 6.83 0 5.58 5.55 0 ...
  .. ..$ gene83  : num [1:100] 7.48 9.39 8.67 8.89 8.96 ...
  .. ..$ gene84  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene85  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene86  : num [1:100] 6.78 0 5 0 0 ...
  .. ..$ gene87  : num [1:100] 0 3.17 5.36 4.7 4.81 ...
  .. ..$ gene88  : num [1:100] 0 0 0 5.32 0 ...
  .. ..$ gene89  : num [1:100] 0 0 0 0 5.91 ...
  .. ..$ gene90  : num [1:100] 6.15 5.25 3.17 5.21 0 ...
  .. ..$ gene91  : num [1:100] 5.29 5.73 4.64 5.04 0 ...
  .. ..$ gene92  : num [1:100] 6.13 3.91 5.83 6.7 7.3 ...
  .. ..$ gene93  : num [1:100] 5.21 6.29 7.29 5.25 0 ...
  .. ..$ gene94  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene95  : num [1:100] 1 0 3.17 3.91 0 ...
  .. ..$ gene96  : num [1:100] 0 5.95 8.21 7 0 ...
  .. ..$ gene97  : num [1:100] 0 0 0 2 3.32 ...
  .. ..$ gene98  : num [1:100] 6.25 6.29 6.3 6.43 6.67 ...
  .. ..$ gene99  : num [1:100] 7.45 7.84 8.51 9.76 10.07 ...
  .. .. [list output truncated]
  ..$ 3:'data.frame':	100 obs. of  1250 variables:
  .. ..$ gene1   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene2   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene3   : num [1:100] 8.79 7.31 6.17 7.7 7.29 ...
  .. ..$ gene4   : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene5   : num [1:100] 3 0 6.43 7.17 4.64 ...
  .. ..$ gene6   : num [1:100] 5.04 7.29 0 4.25 5.73 ...
  .. ..$ gene7   : num [1:100] 6.61 7.73 4.95 6.54 2 ...
  .. ..$ gene8   : num [1:100] 3.17 3.32 7.45 7.98 3.91 ...
  .. ..$ gene9   : num [1:100] 0 6.54 6.27 6.92 6.82 ...
  .. ..$ gene10  : num [1:100] 8.76 8.5 10.27 9.1 10.23 ...
  .. ..$ gene11  : num [1:100] 6.99 3.17 7.42 5.04 6.95 ...
  .. ..$ gene12  : num [1:100] 7.6 7.63 6.87 6.78 7.71 ...
  .. ..$ gene13  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene14  : num [1:100] 5.55 3.32 6.52 6.11 6.95 ...
  .. ..$ gene15  : num [1:100] 5.91 6.07 6.97 0 0 ...
  .. ..$ gene16  : num [1:100] 5.13 0 0 0 0 ...
  .. ..$ gene17  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene18  : num [1:100] 7.29 3.7 6.04 0 6.44 ...
  .. ..$ gene19  : num [1:100] 3.46 7.4 3.7 0 6.19 ...
  .. ..$ gene20  : num [1:100] 7.13 7.67 6.99 7.44 6.44 ...
  .. ..$ gene21  : num [1:100] 5.21 5.7 4.64 0 6.11 ...
  .. ..$ gene22  : num [1:100] 7.51 7.38 7.36 7.02 7.32 ...
  .. ..$ gene23  : num [1:100] 4.17 5.21 5.32 3.46 0 ...
  .. ..$ gene24  : num [1:100] 3.58 4.86 1.58 0 4.91 ...
  .. ..$ gene25  : num [1:100] 6.67 7.47 5.49 7.76 7.61 ...
  .. ..$ gene26  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene27  : num [1:100] 6.58 6.97 5.61 5.49 7.38 ...
  .. ..$ gene28  : num [1:100] 0 5.36 0 5.55 3.46 ...
  .. ..$ gene29  : num [1:100] 0 0 5.67 5.32 0 ...
  .. ..$ gene30  : num [1:100] 4.91 7.64 8.27 6.66 5.67 ...
  .. ..$ gene31  : num [1:100] 6.32 6.81 7.29 3 5.86 ...
  .. ..$ gene32  : num [1:100] 0 0 0 0 0 0 0 0 0 0 ...
  .. ..$ gene33  : num [1:100] 6.48 0 0 0 0 ...
  .. ..$ gene34  : num [1:100] 0 0 0 0 0 ...
  .. ..$ gene35  : num [1:100] 5.81 4.46 5.61 0 0 ...
  .. ..$ gene36  : num [1:100] 0 8.51 8.2 9.91 5.55 ...
  .. ..$ gene37  : num [1:100] 6.17 6.6 0 6.55 7.55 ...
  .. ..$ gene38  : num [1:100] 6.13 4.09 0 6.15 3.17 ...
  .. ..$ gene39  : num [1:100] 0 0 3.46 5.98 5.17 ...
  .. ..$ gene40  : num [1:100] 6.02 6.69 0 5.43 6.48 ...
  .. ..$ gene41  : num [1:100] 8.44 8.44 8.36 9.33 9.23 ...
  .. ..$ gene42  : num [1:100] 2.32 4.46 6.48 6.38 3.81 ...
  .. ..$ gene43  : num [1:100] 5.13 6.09 0 0 3.17 ...
  .. ..$ gene44  : num [1:100] 6 5.29 0 5.81 0 ...
  .. ..$ gene45  : num [1:100] 0 2.58 0 0 0 ...
  .. ..$ gene46  : num [1:100] 5.36 0 4.58 0 0 ...
  .. ..$ gene47  : num [1:100] 0 7.22 5.83 6.29 5.36 ...
  .. ..$ gene48  : num [1:100] 4.7 3.46 0 4.58 6.09 ...
  .. ..$ gene49  : num [1:100] 7.11 4.81 4.64 0 5.83 ...

In [80]:
SIGN <- 0
result <- SINCERITITES(DATA, distance=1, method = 1, noDIAG = 0, SIGN = SIGN)

Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”
Warning message in ks.test.default(p1, p2):
“p-value will be approximate in the presence of ties”

In [81]:
adj_matrix <- result$adj_matrix

In [82]:
dimnames(adj_matrix) <- list(DATA$genes,DATA$genes)

In [83]:
edge_df <- melt(adj_matrix, varnames = c("TF", "Target"), value.name = "Score")

In [84]:
edge_df

        TF       Target   Score
1       gene1    gene1    0.000000e+00
2       gene2    gene1    2.603028e-37
3       gene3    gene1    5.944476e-38
4       gene4    gene1    0.000000e+00
5       gene5    gene1    2.364009e-37
6       gene6    gene1    4.228377e-38
7       gene7    gene1    0.000000e+00
8       gene8    gene1    0.000000e+00
9       gene9    gene1    3.180317e-38
10      gene10   gene1    1.119272e-38
11      gene11   gene1    2.386045e-38
12      gene12   gene1    1.565454e-37
13      gene13   gene1    1.571184e-38
14      gene14   gene1    0.000000e+00
15      gene15   gene1    1.214010e-38
16      gene16   gene1    0.000000e+00
17      gene17   gene1    0.000000e+00
18      gene18   gene1    0.000000e+00
19      gene19   gene1    8.432022e-38
20      gene20   gene1    0.000000e+00
21      gene21   gene1    4.506421e-38
22      gene22   gene1    9.556025e-38
23      gene23   gene1    8.658720e-38
24      gene24   gene1    7.946068e-38
25      gene25   gene1    0.000000e+00
26      gene26   gene1    7.932194e-39
27      gene27   gene1    6.075541e-39
28      gene28   gene1    0.000000e+00
29      gene29   gene1    0.000000e+00
30      gene30   gene1    3.807127e-38
⋮       ⋮        ⋮        ⋮
1562471 gene1221 gene1250 0.000000e+00
1562472 gene1222 gene1250 5.872916e-38
1562473 gene1223 gene1250 2.036568e-36
1562474 gene1224 gene1250 1.541073e-37
1562475 gene1225 gene1250 0.000000e+00
1562476 gene1226 gene1250 4.483706e-37
1562477 gene1227 gene1250 9.535630e-38
1562478 gene1228 gene1250 1.929697e-37
1562479 gene1229 gene1250 2.321920e-36
1562480 gene1230 gene1250 0.000000e+00
1562481 gene1231 gene1250 0.000000e+00
1562482 gene1232 gene1250 0.000000e+00
1562483 gene1233 gene1250 0.000000e+00
1562484 gene1234 gene1250 0.000000e+00
1562485 gene1235 gene1250 1.139987e-37
1562486 gene1236 gene1250 4.103214e-37
1562487 gene1237 gene1250 1.115478e-37
1562488 gene1238 gene1250 1.323576e-36
1562489 gene1239 gene1250 0.000000e+00
1562490 gene1240 gene1250 2.749585e-37
1562491 gene1241 gene1250 6.113846e-37
1562492 gene1242 gene1250 6.523868e-37
1562493 gene1243 gene1250 0.000000e+00
1562494 gene1244 gene1250 0.000000e+00
1562495 gene1245 gene1250 0.000000e+00
1562496 gene1246 gene1250 0.000000e+00
1562497 gene1247 gene1250 2.995222e-37
1562498 gene1248 gene1250 2.991674e-39
1562499 gene1249 gene1250 4.708459e-37
1562500 gene1250 gene1250 0.000000e+00

In [85]:
write.csv(edge_df, file = file.path(path, paste0("SINCERITIES.csv")), row.names = F)